// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

// 转 String
encode<T>(data) {
  data is T ? json.encode(data) : data;
}

// 转 List
decodeList<T>(data) {
  data is List
      ? data.cast<T>()
      : json.decode(data).map<T>((e) => e as T).toList();
}

// 转 Map
decodeMap(data) {
  data is Map
      ? data as Map<String, dynamic>
      : json.decode(data) as Map<String, dynamic>;
}

UserInfo _$UserInfoFromJson(Map<String, dynamic> jsonData) => UserInfo(
      jsonData['userId'] as int,
      jsonData['deptId'] as int,
      jsonData['loginName'] as String,
      jsonData['userName'] as String,
      jsonData['userType'] as String,
      jsonData['email'] as String,
      jsonData['phonenumber'] as String,
      jsonData['sex'] as String,
      jsonData['avatar'] as String,
      jsonData['password'] as String,
      jsonData['salt'] as String,
      jsonData['status'] as String,
      jsonData['delFlag'] as String,
      jsonData['loginIp'] as String,
      decodeList<int>(jsonData['loginDate']) as List<int>,
      jsonData['createBy'] as String,
      jsonData['createTime'] as String,
      jsonData['updateBy'] as String,
      jsonData['updateTime'] as String,
      jsonData['remark'] as String,
      jsonData['openId'] as String,
      jsonData['city'] as String,
      jsonData['country'] as String,
      jsonData['province'] as String,
      jsonData['headimgUrl'] as String,
      jsonData['unionId'] as String,
      jsonData['loginnum'] as int,
      jsonData['userpost'] as String,
      jsonData['businesscity'] as String,
      jsonData['businessprovince'] as String,
      jsonData['organize'] as String,
      jsonData['isnotcie'] as int,
      jsonData['subusername'] as String,
      jsonData['deptType'] as String,
      jsonData['deptTypeName'] as String,
      jsonData['deptStatus'] as String,
      jsonData['usenum'] as String,
      jsonData['expireDate'] as String,
      jsonData['aicLicense'] as int,
      jsonData['aicBalance'] as int,
      jsonData['payType'] as String,
      jsonData['recommenderName'] as String,
      jsonData['recommenderPhone'] as String,
      jsonData['addeffectTime'] as int,
      jsonData['agencyPolicy'] as String,
      jsonData['violation'] as int,
      jsonData['voice'] as int,
      jsonData['myCustomer'] as int,
      jsonData['customerView'] as int,
      jsonData['phone'] as int,
      jsonData['infoModify'] as int,
      jsonData['edit'] as int,
      jsonData['downloadFlag'] as int,
      jsonData['aiFlag'] as int,
      jsonData['addCustomer'] as int,
      jsonData['picUpload'] as int,
      jsonData['excel'] as int,
      jsonData['fclass'] as int,
      jsonData['fclassFree'] as int,
      jsonData['agentFlag'] as int,
      jsonData['myGroup'] as int,
      jsonData['subInfoModify'] as int,
      jsonData['subPhone'] as int,
      jsonData['subEdit'] as int,
      jsonData['subDownload'] as int,
      jsonData['freeMaterials'] as int,
      jsonData['phoneNumbers'] as int,
      jsonData['assistAccount'] as int,
      jsonData['analysis'] as int,
      jsonData['message'] as int,
      jsonData['submitCount'] as String,
      jsonData['ocrErrorCount'] as String,
      jsonData['plateErrorCount'] as String,
      jsonData['repeatCount'] as String,
      jsonData['queueCount'] as String,
      jsonData['passCount'] as String,
      jsonData['matchCount'] as String,
      jsonData['matchRate'] as String,
      jsonData['submitCountYe'] as String,
      jsonData['ocrErrorCountYe'] as String,
      jsonData['plateErrorCountYe'] as String,
      jsonData['repeatCountYe'] as String,
      jsonData['queueCountYe'] as String,
      jsonData['passCountYe'] as String,
      jsonData['matchCountYe'] as String,
      jsonData['matchRateYe'] as String,
      jsonData['headimg'] as String,
      jsonData['recentDay'] as String,
      jsonData['expire'] as int,
      Record.fromJson(decodeMap(jsonData['record']) as Map<String, dynamic>),
    );

Map<String, dynamic> _$UserInfoToJson(UserInfo instance) => <String, dynamic>{
      'userId': instance.userId,
      'deptId': instance.deptId,
      'loginName': instance.loginName,
      'userName': instance.userName,
      'userType': instance.userType,
      'email': instance.email,
      'phonenumber': instance.phonenumber,
      'sex': instance.sex,
      'avatar': instance.avatar,
      'password': instance.password,
      'salt': instance.salt,
      'status': instance.status,
      'delFlag': instance.delFlag,
      'loginIp': instance.loginIp,
      'loginDate': encode(instance.loginDate),
      'createBy': instance.createBy,
      'createTime': instance.createTime,
      'updateBy': instance.updateBy,
      'updateTime': instance.updateTime,
      'remark': instance.remark,
      'openId': instance.openId,
      'city': instance.city,
      'country': instance.country,
      'province': instance.province,
      'headimgUrl': instance.headimgUrl,
      'unionId': instance.unionId,
      'loginnum': instance.loginnum,
      'userpost': instance.userpost,
      'businesscity': instance.businesscity,
      'businessprovince': instance.businessprovince,
      'organize': instance.organize,
      'isnotcie': instance.isnotcie,
      'subusername': instance.subusername,
      'deptType': instance.deptType,
      'deptTypeName': instance.deptTypeName,
      'deptStatus': instance.deptStatus,
      'usenum': instance.usenum,
      'expireDate': instance.expireDate,
      'aicLicense': instance.aicLicense,
      'aicBalance': instance.aicBalance,
      'payType': instance.payType,
      'recommenderName': instance.recommenderName,
      'recommenderPhone': instance.recommenderPhone,
      'addeffectTime': instance.addeffectTime,
      'agencyPolicy': instance.agencyPolicy,
      'violation': instance.violation,
      'voice': instance.voice,
      'myCustomer': instance.myCustomer,
      'customerView': instance.customerView,
      'phone': instance.phone,
      'infoModify': instance.infoModify,
      'edit': instance.edit,
      'downloadFlag': instance.downloadFlag,
      'aiFlag': instance.aiFlag,
      'addCustomer': instance.addCustomer,
      'picUpload': instance.picUpload,
      'excel': instance.excel,
      'fclass': instance.fclass,
      'fclassFree': instance.fclassFree,
      'agentFlag': instance.agentFlag,
      'myGroup': instance.myGroup,
      'subInfoModify': instance.subInfoModify,
      'subPhone': instance.subPhone,
      'subEdit': instance.subEdit,
      'subDownload': instance.subDownload,
      'freeMaterials': instance.freeMaterials,
      'phoneNumbers': instance.phoneNumbers,
      'assistAccount': instance.assistAccount,
      'analysis': instance.analysis,
      'message': instance.message,
      'submitCount': instance.submitCount,
      'ocrErrorCount': instance.ocrErrorCount,
      'plateErrorCount': instance.plateErrorCount,
      'repeatCount': instance.repeatCount,
      'queueCount': instance.queueCount,
      'passCount': instance.passCount,
      'matchCount': instance.matchCount,
      'matchRate': instance.matchRate,
      'submitCountYe': instance.submitCountYe,
      'ocrErrorCountYe': instance.ocrErrorCountYe,
      'plateErrorCountYe': instance.plateErrorCountYe,
      'repeatCountYe': instance.repeatCountYe,
      'queueCountYe': instance.queueCountYe,
      'passCountYe': instance.passCountYe,
      'matchCountYe': instance.matchCountYe,
      'matchRateYe': instance.matchRateYe,
      'headimg': instance.headimg,
      'recentDay': instance.recentDay,
      'expire': instance.expire,
      'record': encode(instance.record),
    };

Record _$RecordFromJson(Map<String, dynamic> json) => Record(
      json['userId'] as int,
      json['submitCount'] as int,
      json['ocrErrorCount'] as String,
      json['plateErrorCount'] as String,
      json['repeatCount'] as String,
      json['queueCount'] as String,
      json['passCount'] as String,
      json['matchCount'] as String,
      json['matchRate'] as String,
      json['submitCountYe'] as String,
      json['ocrErrorCountYe'] as String,
      json['plateErrorCountYe'] as String,
      json['repeatCountYe'] as String,
      json['queueCountYe'] as String,
      json['passCountYe'] as String,
      json['matchCountYe'] as String,
      json['matchRateYe'] as String,
      json['recentDay'] as String,
      json['createTime'] as String,
      json['updateTime'] as String,
    );

Map<String, dynamic> _$RecordToJson(Record instance) => <String, dynamic>{
      'userId': instance.userId,
      'submitCount': instance.submitCount,
      'ocrErrorCount': instance.ocrErrorCount,
      'plateErrorCount': instance.plateErrorCount,
      'repeatCount': instance.repeatCount,
      'queueCount': instance.queueCount,
      'passCount': instance.passCount,
      'matchCount': instance.matchCount,
      'matchRate': instance.matchRate,
      'submitCountYe': instance.submitCountYe,
      'ocrErrorCountYe': instance.ocrErrorCountYe,
      'plateErrorCountYe': instance.plateErrorCountYe,
      'repeatCountYe': instance.repeatCountYe,
      'queueCountYe': instance.queueCountYe,
      'passCountYe': instance.passCountYe,
      'matchCountYe': instance.matchCountYe,
      'matchRateYe': instance.matchRateYe,
      'recentDay': instance.recentDay,
      'createTime': instance.createTime,
      'updateTime': instance.updateTime,
    };
