// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'user_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

UserInfo _$UserInfoFromJson(Map<String, dynamic> json) => UserInfo(
      json['userId'] as int,
      json['deptId'] as int,
      json['loginName'] as String,
      json['userName'] as String,
      json['userType'] as String,
      json['email'] as String,
      json['phonenumber'] as String,
      json['sex'] as String,
      json['avatar'] as String,
      json['password'] as String,
      json['salt'] as String,
      json['status'] as String,
      json['delFlag'] as String,
      json['loginIp'] as String,
      (json['loginDate'] as List<dynamic>).map((e) => e as int).toList(),
      json['createBy'] as String,
      json['createTime'] as String,
      json['updateBy'] as String,
      json['updateTime'] as String,
      json['remark'] as String,
      json['openId'] as String,
      json['city'] as String,
      json['country'] as String,
      json['province'] as String,
      json['headimgUrl'] as String,
      json['unionId'] as String,
      json['loginnum'] as int,
      json['userpost'] as String,
      json['businesscity'] as String,
      json['businessprovince'] as String,
      json['organize'] as String,
      json['isnotcie'] as int,
      json['subusername'] as String,
      json['deptType'] as String,
      json['deptTypeName'] as String,
      json['deptStatus'] as String,
      json['usenum'] as String,
      json['expireDate'] as String,
      json['aicLicense'] as int,
      json['aicBalance'] as int,
      json['payType'] as String,
      json['recommenderName'] as String,
      json['recommenderPhone'] as String,
      json['addeffectTime'] as int,
      json['agencyPolicy'] as String,
      json['violation'] as int,
      json['voice'] as int,
      json['myCustomer'] as int,
      json['customerView'] as int,
      json['phone'] as int,
      json['infoModify'] as int,
      json['edit'] as int,
      json['downloadFlag'] as int,
      json['aiFlag'] as int,
      json['addCustomer'] as int,
      json['picUpload'] as int,
      json['excel'] as int,
      json['fclass'] as int,
      json['fclassFree'] as int,
      json['agentFlag'] as int,
      json['myGroup'] as int,
      json['subInfoModify'] as int,
      json['subPhone'] as int,
      json['subEdit'] as int,
      json['subDownload'] as int,
      json['freeMaterials'] as int,
      json['phoneNumbers'] as int,
      json['assistAccount'] as int,
      json['analysis'] as int,
      json['message'] as int,
      json['submitCount'] as String,
      json['ocrErrorCount'] as String,
      json['plateErrorCount'] as String,
      json['repeatCount'] as String,
      json['queueCount'] as String,
      json['passCount'] as String,
      json['matchCount'] as String,
      json['matchRate'] as String,
      json['submitCountYe'] as String,
      json['ocrErrorCountYe'] as String,
      json['plateErrorCountYe'] as String,
      json['repeatCountYe'] as String,
      json['queueCountYe'] as String,
      json['passCountYe'] as String,
      json['matchCountYe'] as String,
      json['matchRateYe'] as String,
      json['headimg'] as String,
      json['recentDay'] as String,
      json['expire'] as int,
      Record.fromJson(json['record'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$UserInfoToJson(UserInfo instance) => <String, dynamic>{
      'userId': instance.userId,
      'deptId': instance.deptId,
      'loginName': instance.loginName,
      'userName': instance.userName,
      'userType': instance.userType,
      'email': instance.email,
      'phonenumber': instance.phonenumber,
      'sex': instance.sex,
      'avatar': instance.avatar,
      'password': instance.password,
      'salt': instance.salt,
      'status': instance.status,
      'delFlag': instance.delFlag,
      'loginIp': instance.loginIp,
      'loginDate': instance.loginDate,
      'createBy': instance.createBy,
      'createTime': instance.createTime,
      'updateBy': instance.updateBy,
      'updateTime': instance.updateTime,
      'remark': instance.remark,
      'openId': instance.openId,
      'city': instance.city,
      'country': instance.country,
      'province': instance.province,
      'headimgUrl': instance.headimgUrl,
      'unionId': instance.unionId,
      'loginnum': instance.loginnum,
      'userpost': instance.userpost,
      'businesscity': instance.businesscity,
      'businessprovince': instance.businessprovince,
      'organize': instance.organize,
      'isnotcie': instance.isnotcie,
      'subusername': instance.subusername,
      'deptType': instance.deptType,
      'deptTypeName': instance.deptTypeName,
      'deptStatus': instance.deptStatus,
      'usenum': instance.usenum,
      'expireDate': instance.expireDate,
      'aicLicense': instance.aicLicense,
      'aicBalance': instance.aicBalance,
      'payType': instance.payType,
      'recommenderName': instance.recommenderName,
      'recommenderPhone': instance.recommenderPhone,
      'addeffectTime': instance.addeffectTime,
      'agencyPolicy': instance.agencyPolicy,
      'violation': instance.violation,
      'voice': instance.voice,
      'myCustomer': instance.myCustomer,
      'customerView': instance.customerView,
      'phone': instance.phone,
      'infoModify': instance.infoModify,
      'edit': instance.edit,
      'downloadFlag': instance.downloadFlag,
      'aiFlag': instance.aiFlag,
      'addCustomer': instance.addCustomer,
      'picUpload': instance.picUpload,
      'excel': instance.excel,
      'fclass': instance.fclass,
      'fclassFree': instance.fclassFree,
      'agentFlag': instance.agentFlag,
      'myGroup': instance.myGroup,
      'subInfoModify': instance.subInfoModify,
      'subPhone': instance.subPhone,
      'subEdit': instance.subEdit,
      'subDownload': instance.subDownload,
      'freeMaterials': instance.freeMaterials,
      'phoneNumbers': instance.phoneNumbers,
      'assistAccount': instance.assistAccount,
      'analysis': instance.analysis,
      'message': instance.message,
      'submitCount': instance.submitCount,
      'ocrErrorCount': instance.ocrErrorCount,
      'plateErrorCount': instance.plateErrorCount,
      'repeatCount': instance.repeatCount,
      'queueCount': instance.queueCount,
      'passCount': instance.passCount,
      'matchCount': instance.matchCount,
      'matchRate': instance.matchRate,
      'submitCountYe': instance.submitCountYe,
      'ocrErrorCountYe': instance.ocrErrorCountYe,
      'plateErrorCountYe': instance.plateErrorCountYe,
      'repeatCountYe': instance.repeatCountYe,
      'queueCountYe': instance.queueCountYe,
      'passCountYe': instance.passCountYe,
      'matchCountYe': instance.matchCountYe,
      'matchRateYe': instance.matchRateYe,
      'headimg': instance.headimg,
      'recentDay': instance.recentDay,
      'expire': instance.expire,
      'record': instance.record,
    };

Record _$RecordFromJson(Map<String, dynamic> json) => Record(
      json['userId'] as int,
      json['submitCount'] as int,
      json['ocrErrorCount'] as String,
      json['plateErrorCount'] as String,
      json['repeatCount'] as String,
      json['queueCount'] as String,
      json['passCount'] as String,
      json['matchCount'] as String,
      json['matchRate'] as String,
      json['submitCountYe'] as String,
      json['ocrErrorCountYe'] as String,
      json['plateErrorCountYe'] as String,
      json['repeatCountYe'] as String,
      json['queueCountYe'] as String,
      json['passCountYe'] as String,
      json['matchCountYe'] as String,
      json['matchRateYe'] as String,
      json['recentDay'] as String,
      json['createTime'] as String,
      json['updateTime'] as String,
    );

Map<String, dynamic> _$RecordToJson(Record instance) => <String, dynamic>{
      'userId': instance.userId,
      'submitCount': instance.submitCount,
      'ocrErrorCount': instance.ocrErrorCount,
      'plateErrorCount': instance.plateErrorCount,
      'repeatCount': instance.repeatCount,
      'queueCount': instance.queueCount,
      'passCount': instance.passCount,
      'matchCount': instance.matchCount,
      'matchRate': instance.matchRate,
      'submitCountYe': instance.submitCountYe,
      'ocrErrorCountYe': instance.ocrErrorCountYe,
      'plateErrorCountYe': instance.plateErrorCountYe,
      'repeatCountYe': instance.repeatCountYe,
      'queueCountYe': instance.queueCountYe,
      'passCountYe': instance.passCountYe,
      'matchCountYe': instance.matchCountYe,
      'matchRateYe': instance.matchRateYe,
      'recentDay': instance.recentDay,
      'createTime': instance.createTime,
      'updateTime': instance.updateTime,
    };
